export const navigation = [ 
    {
    'id'      : 'teamGroup',
    'title'   : 'TEAM',
    'type'    : 'group',
    // 'icon' : 'business_center',
    'url'  : '',
    'children': [
      {
          'id'   : 'teams',
          'title': 'My Teams',
          // 'translate': 'NAV.SAMPLE.TITLE',
          'type' : 'item',
          'icon' : 'business_center',
          'url'  : '/team/all',
          'hidden' : false,
      },
      {
        'id'   : 'focusTeam',
        'title': 'ABC Co.',
        'type' : 'item',
        'icon' : 'business_center',
        'url'  : '',
        'hidden' : true,
    },
    ]},
    {
      'id'      : 'projectGroup',
      'title'   : 'PROJECTS',
      'type'    : 'group',
      'hidden' : true,
      // 'icon' : 'business_center',
      'url'  : '',
      'children': [
        {
            'id'   : 'projects',
            'title': 'My Projects',
            // 'translate': 'NAV.SAMPLE.TITLE',
            'type' : 'item',
            // 'icon' : 'business_center',
            'url'  : 'project/all',
            'hidden' : true,
        },
        {
          'id'   : 'focusProject',
          'title': 'Test Project',
          'type' : 'item',
          'icon' : 'business_center',
          'url'  : 'focusproject_url',
          'hidden' : true,
      },
      ]},
      {
        'id'      : 'topicGroup',
        'title'   : 'TOPIC',
        'type'    : 'group',
        // 'icon' : 'business_center',
        'url'  : '',
        'hidden' : true,
        'children': [
          {
              'id'   : 'topics',
              'title': 'My sub-projects and Topics',
              // 'translate': 'NAV.SAMPLE.TITLE',
              'type' : 'item',
              // 'icon' : 'business_center',
              'url'  : 'topic/all',
              'hidden' : true,
          },
          {
            'id'   : 'focusTopic',
            'title': 'Issue 123',
            'type' : 'item',
            // 'icon' : 'business_center',
            'url'  : 'focusTopic_url',
            'hidden' : true,
        },
        ]},
        {
          'id'      : 'favouritsGroup',
          'title'   : 'FAVOURITES',
          'type'    : 'group',
          // 'icon' : 'business_center',
          'url'  : '',
          'children': [
            {
                'id'   : 'fav001',
                'title': 'Issue 123',
                // 'translate': 'NAV.SAMPLE.TITLE',
                'type' : 'item',
                // 'icon' : 'business_center',
                'url'  : '',
            },
            {
              'id'   : 'fav002',
              'title': 'Project XYZ',
              'type' : 'item',
              // 'icon' : 'business_center',
              'url'  : '',
          },
          ]},
  
  ];
